security:
    encoders:
        FOS\UserBundle\Model\UserInterface: md5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CLIENT: ROLE_CLIENT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            provider:     fos_userbundle
            pattern: ^/
            form_login:
                login_path : fos_user_security_login
                check_path: fos_user_security_check
                default_target_path:  fos_user_profile_show
            logout:
                path:       logout
                target:     login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }